AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Infrastructure for dbowland.com jokes project

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      certificate: adce1a21-90b4-4120-8548-111215e582f0
      domain: dbowland.com
      lambdaBucketName: jokes-lambda
      project: jokes
      roleNameCloudFormation: jokes-cloudformation
      roleNamePipeline: jokes-pipeline
    test:
      certificate: 6a48cba7-feb9-4de5-8cbf-d383140fcdef
      domain: bowland.link
      lambdaBucketName: jokes-lambda-test
      project: jokes-test
      roleNameCloudFormation: jokes-cloudformation-test
      roleNamePipeline: jokes-pipeline-test

Resources:
  # Authentication

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        DeviceOnlyRememberedOnUserPrompt: true
      EmailConfiguration:
        ReplyToEmailAddress: !Sub
          - 'do-not-reply@${Domain}'
          - Domain: !FindInMap [EnvironmentMap, !Ref Environment, domain]
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      MfaConfiguration: OPTIONAL
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 14
      SmsAuthenticationMessage: Your authentication code is {####}.
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      UserPoolName: !FindInMap [EnvironmentMap, !Ref Environment, project]
      UserPoolTags:
        'created-by': 'jokes-infrastructure'
        'created-for': 'jokes'
        'environment': !Ref Environment

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 1 # Hours
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - !Sub
          - 'https://jokes.${Domain}'
          - Domain: !FindInMap [EnvironmentMap, !Ref Environment, domain]
      IdTokenValidity: 1 # Hours
      LogoutURLs:
        - !Sub
          - 'https://jokes.${Domain}'
          - Domain: !FindInMap [EnvironmentMap, !Ref Environment, domain]
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30 # Days
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref UserPool

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      CustomDomainConfig:
        CertificateArn: !Sub
          - 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${Certificate}'
          - Certificate: !FindInMap [EnvironmentMap, !Ref Environment, certificate]
      Domain: !Sub
        - 'jokes-auth.${DomainName}'
        - DomainName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
      UserPoolId: !Ref UserPool

  # Authorization

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowClassicFlow: false
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !Sub '${UserPool.ProviderName}'
      IdentityPoolName: !FindInMap [EnvironmentMap, !Ref Environment, project]

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        'authenticated': !Sub '${AuthenticatedRole.Arn}'
        'unauthenticated': !Sub '${UnauthenticatedRole.Arn}'

  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - cognito-identity.amazonaws.com
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud:
                  - !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr:
                  - authenticated
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/root-boundary'
      Tags:
        - Key: 'created-by'
          Value: 'jokes-infrastructure'
        - Key: 'created-for'
          Value: 'jokes'
        - Key: 'environment'
          Value: !Ref Environment

  UnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - cognito-identity.amazonaws.com
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud:
                  - !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr:
                  - unauthenticated
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/root-boundary'
      Tags:
        - Key: 'created-by'
          Value: 'jokes-infrastructure'
        - Key: 'created-for'
          Value: 'jokes'
        - Key: 'environment'
          Value: !Ref Environment

  # Deployment storage

  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !FindInMap [EnvironmentMap, !Ref Environment, lambdaBucketName]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'created-by'
          Value: 'jokes-infrastructure'
        - Key: 'created-for'
          Value: 'jokes'
        - Key: 'environment'
          Value: !Ref Environment

  # Deployment roles

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub
            - '${Project}-cloudformation'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                NotAction:
                  - 'iam:*User'
                  - 'organizations:*'
                  - 'account:*'
                Resource: '*'
      RoleName: !FindInMap [EnvironmentMap, !Ref Environment, roleNameCloudFormation]
      Tags:
        - Key: 'created-by'
          Value: 'jokes-infrastructure'
        - Key: 'created-for'
          Value: 'jokes'
        - Key: 'environment'
          Value: !Ref Environment

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${AWS::AccountId}'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub
            - '${Project}-pipeline'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !Sub '${CloudFormationRole.Arn}'
              - Effect: Allow
                Action: 'cloudformation:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:DeleteObject'
                  - 's3:GetObject*'
                  - 's3:PutObject*'
                  - 's3:GetBucket*'
                  - 's3:List*'
                Resource:
                  - 'arn:aws:s3:::jokes-ui-source/*'
                  - 'arn:aws:s3:::jokes-ui-source'
                  - 'arn:aws:s3:::jokes-ui-test/*'
                  - 'arn:aws:s3:::jokes-ui-test'
                  - !Sub 'arn:aws:s3:::${LambdaBucket}/*'
                  - !Sub 'arn:aws:s3:::${LambdaBucket}'
      RoleName: !FindInMap [EnvironmentMap, !Ref Environment, roleNamePipeline]
      Tags:
        - Key: 'created-by'
          Value: 'jokes-infrastructure'
        - Key: 'created-for'
          Value: 'jokes'
        - Key: 'environment'
          Value: !Ref Environment

  # Deployment users

  ApiUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub
            - '${Project}-pipeline'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/jokes-pipeline'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/jokes-pipeline-test'
      Tags:
        - Key: 'created-by'
          Value: 'jokes-infrastructure'
        - Key: 'created-for'
          Value: 'jokes'
        - Key: 'environment'
          Value: !Ref Environment

  UiUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub
            - '${Project}-pipeline'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/jokes-pipeline'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/jokes-pipeline-test'
      Tags:
        - Key: 'created-by'
          Value: 'jokes-infrastructure'
        - Key: 'created-for'
          Value: 'jokes'
        - Key: 'environment'
          Value: !Ref Environment

Outputs:
  UserPoolDomainName:
    Description: Domain name for user pool
    Value: !Sub
      - 'jokes-auth.${DomainName}'
      - DomainName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
